### ISSUE TITLE
Migrate data from old database to datasets, revisions, piplelines 

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#11]
#Currently, all pipelines and their history is kept in `spec` table in database. As we upgraded to FlowManager that maintains data in several different tables (datasets, their revisions and pipelines) we need to migrate old data to new tables, so that we do not loose data

## Acceptance criteria

* [ ] no data is lost while migration

## Tasks

* [x] write script (prob locally) that will get data from `spec` table and put it into new tables appropriatelly 
  * [x] probably use `upload()` method of FlowManager
* [x] do this with local db
* [x] deploy to testing db and run tests
* [x] if all above suceeds deploy to production

**Comment by zelima** [comment]
FIXED
