### ISSUE TITLE
Status info and status for specific revision

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#17]
We need to get status and info for specific revision not only for latest one

## Acceptance criteria

* [x] able to get status and info for given revision

## Tasks 

* [x] update tests
* [x] merge `status` and `info` into info
* [x] remove `info` from URL
* [x] `/source/{owner}/{id}/info` -> `/source/{owner}/{id}/{revision}`
* [x] `/source/{owner}/{id}/latest` - responds with latest revision  (same with status)
* [x] `/source/{owner}/{id}/successfull` - responds with latest successful revision  (same with status)  
* [x] update README #

**Comment by akariv** [comment]
Make sure that any data appearing in the `status` response is also present in the `info` one (given that it's being used by frontend)

**Comment by zelima** [comment]
@akariv we agreed to merge status and info with @anuveyatsu . Indeed thinking to get rid of `/info` from the url at all:
```
.../source/{owner}/{id}/{revision}
```

**Comment by zelima** [comment]
FIXED
