### ISSUE TITLE
Tests for flow statuses 

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#18]
We need to be sure flow statuses are set correctly - SUCCESS, FAIL, QUEUED, INPROGRESS

## Acceptance criteria

* [x] flow status is according to pipelines' status and is set correctly
* [x] Tested

## Tasks

* [x] add failing test cases
* [x] fix bugs if any

**Comment by zelima** [comment]
FIXED in https://github.com/datahq/specstore/commit/5c4320b5d45eaefc21d08083b97d769c92b0fec8

* No failed, no succes -> PENDING
* One of them failed -> FAILED
* One running -> RUNNING
* No failed, at least one success, at least one pending -> RUNNING
* No failed, no pending, no running -> SUCCESS
