### ISSUE TITLE
Collect errors for each pipeline (and modify stats collection) 

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#21]
We need to modify report for pipelines so that we have in the status API a new member pipelines
* [ ] `pipelines` will have one member per finished pipeline
* [ ] Each of these members will have these properties: `status`, `stats`, `error_log`, `title` 

## Acceptance Criteria

* [x] Errors are recorded for pipelines
* [x] Stats are recorded for each pipelines

## Tasks

* [x] analysis
* [x] write tests
* [x] refactor code

### Alternate solution (see analysis below)

Currently, we have `errors`, `logs` and `stats` columns in dataset revision table. Instead, we can have
one column `pipelines` where we can have errors, logs and stats for each pipeline.

Or leave other columns as is and add `pipelines` column with them. `errors`, `logs` and `stats` will record the overall flow status and `pipelines` for each

POST `source/update`

```
def handle_update(content):
    errors = content.get('errors')
    event = content['event']
    success = content.get('success')
    log = content.get('log', [])
    stats = content.get('stats', {})
    
    pipeline_info = {errors: errors, log: log, stats: stats, title: title} 
    doc = dict(
        status=pipeline_status,
        errors=errors,
        stats=stats,
        log=log,
        updated_at=now
        pipelines={pipeline_id: pipeline_info }  ## new column in revision table 
    )
    ....
    revision = registry.update_revision(flow_id, doc)
    ....

```

--- 

### What we have (Errors)

Currently, "errors" in dataset revision is a list of strings (error trace separated by newline) Eg ["assembler.sample", "ERROR   :Data Package validation, ....]  and it is always for one (failed) pipeline. We do not record other errors (are there any?), as we delete all pipeline right after we find one of them failed. 

Questions: 
* How we can record errors for each pipeline, as there always be one failed pipeline? 
  * even if we do, would not other error be just `dirty dependency` errors?
* Or we are doing this cause we want to monitor wich pipeline exactly failed and place error log inside `pipline/id` Eg:
```
{
  'core/finance-vix/30/datapackage_report': [logs gere]
}
```

* How to collect errors for each pipeline ? 
  * does this mean 

### What we have (Stats)

We are recording stats for latest pipeline run, together with `{./datahub {pipeline: stats}}` object that keeps stats for each pipeline. We now need to know nice English name provided from planer together with stats.

Questions:

* how the new object will look like? - might this be correct `{./datahub {pipeline: {stats: stats, name: pipeline-name }}}`

### status API

* How are we going to collect all the info for pipelines in one object?

### Conlusion

This is too messy 

----

```
{
  "pipelines": {
      "<pipeline-id>": {
          "title": "Create a ZIP file",
          "status": "FAILED",
          "stats": null,
          "error_log": [
            "error line 1", ...
          ]
      },
      "<pipeline-id-2>": {
          "title": "Validate package contents",
          "status": "SUCCESS",
          "stats": { 
            "bytes": 1234,
            ...
          },
          "error_log": []
      }
  }
}
``` #22

**Comment by zelima** [comment]
FIXED
