### ISSUE TITLE
Move adding datasets to ES index from assembler to specstore

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#28]
Currently, creation and mapping of ES index plus adding dataset to index is happening in [assembler](https://github.com/datahq/assembler/blob/master/datapackage_pipelines_assembler/processors/dump_to_s3.py#L11) service via `dump_ro_s3` (mapping and creation ) and `dump.to_index` (adding datasets) processes. We are moving it here as we want communication with ES to be centralized (events are exported from here)

## Acceptance Criteria

* [x] specstore is responsible for exporting datasets to ES
* [x] we still use `tableschema_elasticsearch` library
* [x] mapping happens from specsre 

## Tasks 

* [x] copy mapping and modify so that it searches in datapackage.reamde
* [x] move [`datapackage-pipelines-elasticsearch`](https://github.com/frictionlessdata/datapackage-pipelines-elasticsearch/blob/master/datapackage_pipelines_elasticsearch/processors/dump/to_index.py) functionality here so that it fits our needs
* [x] Export to datasets ES from `source/update` API once revision is successful 
* [x] remove code from `assembler.dump_to_s3` 
* [x] remove `dump.to_index` processor from planner
* [x] Tests 
* [x] run and pass BB tests for assembler

**Comment by zelima** [comment]
FIXED
