### ISSUE TITLE
[Delete] serve delete API 

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#40]
We are implementing purge commend so we need an API for it. As specstore has access for all involved instances this makes it the best place to serve. 

## Acceptance Criteria

* [ ] User is authorized and Authenticated before deleting anything 
* [ ] After request there is no data either in pkgstrore, metastore, or  specstore

## Tasks

* [ ] Authorization 
  * [ ] Prepare tests
  * [ ] Add function that returns True if authorised 
* [ ] Delete from metastore (Elasticsearch)
  * [ ] Prepare Tests
  * [ ] add apropriate method to datasets https://github.com/datahq/specstore/blob/master/flowmanager/datasets.py
* [ ] Delete from pkgstore (S3)
  * [ ] Prepare tests
  * [ ] appropriate function in models
* [ ] Delete from specstre (database)
  * [ ] Prepare tests 
  * [ ] delete fromdatasets
  * [ ] delete from revisions
* [ ] serve endpoint
