### ISSUE TITLE
Update analyzers to ignore stop words 

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#41]
Originally coming from here https://github.com/datahq/datahub-qa/issues/170

We have to reindex elasticsearch with  `"analyzer": "english"` instead of the `standard` for README, title and description

## Acceptance Criteria 

* [x] If I search The Manua Loa I've got results that does not have "the" in title

## Tasks

* [x] prepare script to reindex localhost
* [x] reindex testing
* [x] reindex production 
* [x] update tests in metastore

**Comment by zelima** [comment]
FIXED in https://github.com/datahq/specstore/pull/42
