### ISSUE TITLE
Storage limit for space

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#45]
Originally coming from 
https://github.com/datahq/datahub-qa/issues/173
https://github.com/datahq/datahub-qa/issues/174

As an admin I want to limit users ability to publish datasets by space they are using. Eg cannot push more than XXX Mb of data. So that I'm able to offer them storage under different plans

As an admin, I want to limit users ability to publish datasets by private space they are using so that I'm able to offer them privacy under different plans
 
## Acceptance Criteria

* [x] user is getting an appropriate error message via CLI that space limit is reached 
* [x] user is getting an appropriate error message via CLI that private space limit is reached

## Tasks

* [x] Do analysis
* [x] Tests
* [x] add function to models to comunicate with file manager
  * [ ] ~~tests with mocked responses~~
* [x] update controllers to check 

## Analysis

Questions to answer:

* Which number is counted for space usage - raw bytes (data pushed by the user), or total bytes (including derived, original etc...)
* Should we count MBs for each revision?

less important 

* Do private and public bites overlap, Or private bites are counted separately? Eg: I have 100 Mb total free space and published 10 mb of private, how much total space I'm left with 90 or 100?
* What if I don't have public storage, but still have private, can I still publish as public?
* What if I have some MBs left in public and some for private, can I use both to publish as public?

Answering Q1:

1. Assuming users do not really care about the size of derived data, we should only count bytes of the data that user pushes (get's in rawstore). 
2. But on the other hand published dataset (tidy, normalized, various formats, views etc...) is the product we offer. 
besides that, we can't know the size of the remote data. 
Also potentially user can create a bunch of derived data with various processing steps out of the single file.

Considering above I'm assuming we should go with option N2

Answering Q2:

Since a user can maintain N number of revisions as the versions of data think we should count.

### How it's gonna work?

Ok so we already serve API to get the total size of storage for an owner and it's available to filter by findability. That means we can simply hit `api.datahub.io/storage/owner/<owner>?findability=<findability>` from specstore and get the needed info.

```python
# in models
from filemanager.models import get_total_size_for_owner

...
  owner = content['meta']['ownerid']
  findability = content['meta']['findability']
  current_storage = get_total_size_for_owner(owner, findability)(owner, findability if findability == private else None)
  max_storage = limits.get('max_private_storage_mb' if findability == 'private' else 'max_public_storage_mb', 0)
  if max_storage < current_storage:
    errors.append('Max Storage for user exceeded plan limit')
  else:
    continue...
```

**Comment by zelima** [comment]
Issue moved to [datahq/bitstore #24](https://github.com/datahq/bitstore/issues/24) via [**ZenHub**](https://www.zenhub.com/)
