### ISSUE TITLE
Rawstore returns 404 when package is processed in some cases

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#48]
Originally coming from https://github.com/datahq/datahub-qa/issues/227

Some revisions are failing for the following reason:

`"tabulator.exceptions.HTTPError: 404 Client Error: Not Found for url: https://s3.amazonaws.com...`

- See full logs - https://api.datahub.io/source/datahq/datahub-kpis/45
- Same thing here - https://api.datahub.io/source/datahq/datahub-kpis/46
- However this was OK - https://api.datahub.io/source/datahq/datahub-kpis/44

## Acceptance Criteria 

* [ ] we know reason why this happens 
* [ ] bug eliminated

## Tasks

* [ ] investigate
* [ ] create test if possible
* [ ] fix the bug

## Analysis

While we could not reproduce this locally, it seems bug was related to CLI generating pre-signed URL asynchronously for rawstore, leading the resource mapping sometimes not containing URLs for all resource. (Though this is not 100% percent sure answer)

**Comment by zelima** [comment]
FIXED. please reopen if repeats
