### ISSUE TITLE
Send incidents when pipelines fail for automated datasets

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#50]
We need the communication layer between statuspage.io and our services so that we can register an incident when any of automated datasets' processors fails so that we send Email notifying about it

## Acceptance Criteria

- [x] Email is sent to subscribed users (core)

## Tasks

- [x] refactor specstore to use https://github.com/datahq/datahub-emails on the broken pipeline
  - [ ] What about when it's fixed?
- [x] update service with proper envs

**Comment by zelima** [comment]
FIXED
