### ISSUE TITLE
[EPIC] Upgrade to FlowManager

### ISSUE THREAD

**Issue by zelima** [datahq/specstore#7]
Currently, specstore is used to, keep simple metadata about flow - such as owner, dataset name, spec content, and creation/update time.  We'd like specstore to be smarter and actually manage whole flow process. We'd like it to keep more information, such as exact flow states,  flow revisions, pipelines and their dependencies.

## Acceptance criteria

* [x] has it's own DB Models, instead of `SourceSpecRegistry` taking care of it
* [x] One flow is run exactly ones 
* [x] pipeline dependencies are monitored from flow-manager

## Tasks

* [x] Create models
  * Dataset, Dataset-Revision, Pipelines
* [x] Actions
  * create/update
  * pipeline status update
* [x] serve endpoint `source/update`
  * [x] controler for updae
* [x] tests
* [x] rename specstore -> flowmanager in files

#### Dataset == flow-spec:
  - identifier (unique per owner)
  - owner
  - a spec
  - last update time

#### Dataset-Revision == flow:
  - dataset==(owner, dataset-identifier)
  - revision (number, monotonically increasing)
  - creation time
  - status
  - errors
  - ...
   
#### Pipelines
  - pipeline identifier
  - flow identifier==(dataset, revision)
  - pipeline datails==(dependencies, steps)
  - status
  - errors
  - last update time
  - ...

#### on *data push*:
  - create new dataset if needed
  - create new revision for dataset
  - use planner for dataset, get list of pipelines
    - prefix with dataset-name/revision-id/
  - store new revision
  - store pipelines in pipelines-db
  
#### on *pipeline status update* (webhook):
  - update pipeline status in db
  - update flow status in db accordingly:
    - all success -> flow success
    - one failed -> flow failed
    - one pending -> flow pending
  - on flow success, delete all its pipelines from pipelines-db

**Comment by zelima** [comment]
FIXED in 65bd525
